version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    restart: always
  db:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./database/db:/data/db
      - ./database/config:/data/configdb
    userns_mode: keep-id
volumes:
  data:
  config: