version: "3"
services:
  redis:
    image: redis
    restart: always
  page_sequence:
    image: ghcr.io/hannahellis4242/sbpss/scala-book-page-sequence-service:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
  sigature_finder:
    image: ghcr.io/hannahellis4242/bsfs/book-signature-finder-service:latest
    restart: always
  signature_order:
    image: ghcr.io/hannahellis4242/bsoo/book-signature-order-options:latest
    restart: always
  web:
    image: ghcr.io/hannahellis4242/book-binder:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
